import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import DescriptionCard from '../component/DescriptionCard'
import ContinuousSlider from '../component/Slider'

export default function Home() {
  let array_1 = [{name: "johndoe", description: "english major"}, {name: "Yuheon Joh", description: "computer science"},
  {name : "Hello", description: "world"}]
  let array_2 = array_1.map((element)=>{return <DescriptionCard name={element.name} description={element.description}></DescriptionCard>})
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        
        {array_2}
        <ContinuousSlider></ContinuousSlider>
        
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
